### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by vweevers** [fczbkk/UrlMatch#2]
What's the state of this project? Can you publish it to npm?

**Comment by fczbkk** [comment]
@vweevers This lib is alive and kicking. I actively use it in my personal projects.

The name `url-match` was already taken at NPM. So I changed it to scoped package. You can find it at:

https://www.npmjs.com/package/@fczbkk/url-match

**Comment by vweevers** [comment]
Aha, that's excellent. Thanks for a great lib
