### ISSUE TITLE
`+` in pathnames

### ISSUE THREAD

**Issue by gromnitsky** [fczbkk/UrlMatch#6]
Using docs/url-match.js

    > let m = new UrlMatch.default('*://*.example.com/*')

I think '+' should be allowed in _pathnames_:

~~~
> m.test('https://www.example.com/foo%20bar')
true
> m.test('https://www.example.com/foo+bar')
false
~~~

**Comment by fczbkk** [comment]
Hey @gromnitsky, I have added support for plus signs in the path. Update to `v3.4.0`, it should work.
