### ISSUE TITLE
Error: UrlMatch is not a constructor

### ISSUE THREAD

**Issue by Cyb3rN8** [fczbkk/UrlMatch#8]
Env:
```json
{
    "@fczbkk/url-match": "^3.5.0",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
}
```

Code:
```typescript
import UrlMatch from "@fczbkk/url-match";

console.log(new UrlMatch(["https://*"]).test("https://www.google.com"));
```

**Comment by fczbkk** [comment]
Hey @nathan-deng-ai, the code you provided seems to be working with no problems for me:
https://codesandbox.io/s/urlmatch-example-77vhjy?file=/src/index.js

I'm closing this issue for now. Feel free to reopen it with a description of steps to replicate the problem.
